# SPDX-License-Identifier: LGPL-2.1-or-later

import _PartDesign

makeFilletArc = _PartDesign.makeFilletArc
getHoleThreadCatalog = _PartDesign.getHoleThreadCatalog
beginDesignOperationEdit = _PartDesign.beginDesignOperationEdit
initializeDesignDefinition = _PartDesign.initializeDesignDefinition
resolveDesignDefinitionReference = _PartDesign.resolveDesignDefinitionReference
resolveDesignDefinitionSubelementReference = (
    _PartDesign.resolveDesignDefinitionSubelementReference
)
initializeDesignBodyFromLegacyFeature = (
    _PartDesign.initializeDesignBodyFromLegacyFeature
)
finalizeDesignDefinition = _PartDesign.finalizeDesignDefinition
setDesignOperationTargets = _PartDesign.setDesignOperationTargets
setDesignFeaturePatternTargets = _PartDesign.setDesignFeaturePatternTargets
setDesignBodyPatternSource = _PartDesign.setDesignBodyPatternSource
setDesignCloneSource = _PartDesign.setDesignCloneSource
setDesignScriptOutputs = _PartDesign.setDesignScriptOutputs
setDesignCombineBodies = _PartDesign.setDesignCombineBodies
setDesignSplitDefinition = _PartDesign.setDesignSplitDefinition
assignDesignSplitRegions = _PartDesign.assignDesignSplitRegions
setDesignSeparateDefinition = _PartDesign.setDesignSeparateDefinition
finalizeDesignOperationEdit = _PartDesign.finalizeDesignOperationEdit
finalizeDesignScriptOperationEdit = _PartDesign.finalizeDesignScriptOperationEdit
removeDesignOperation = _PartDesign.removeDesignOperation
validateDesign = _PartDesign.validateDesign
