// SPDX-License-Identifier: LGPL-2.1-or-later

/***************************************************************************
 *   Copyright (c) 2007
 * Jürgen Riegel <juergen.riegel@web.de>              *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

#include <sstream>
#include <unordered_set>

#include <Base/FileInfo.h>
#include <Base/Interpreter.h>
#include <Base/Stream.h>

#include "Application.h"
#include "Document.h"
#include "DocumentObject.h"
#include "DocumentObjectPy.h"
#include "DocumentTimeline.h"
#include "MergeDocuments.h"

// inclusion of the generated files (generated By DocumentPy.xml)
#include "DocumentPy.h"
#include "DocumentPy.cpp"
#include <boost/regex.hpp>
#include <Base/PyWrapParseTupleAndKeywords.h>

using namespace App;

namespace
{

Py::Object snapshotPythonSequence(PyObject* value, const char* message)
{
    PyObject* sequence = PySequence_Fast(value, message);
    if (!sequence) {
        throw Py::Exception();
    }
    return Py::Object(sequence, true);
}

void validateParsedDocumentObject(const Document* document, const DocumentObject* object, const char* message)
{
    if (!document || !object || !document->containsObject(object)
        || object->getDocument() != document) {
        throw Py::ValueError(message);
    }
}

void validateParsedDocumentObjects(
    const Document* document,
    const std::vector<DocumentObject*>& objects,
    const char* message
)
{
    for (const auto* object : objects) {
        validateParsedDocumentObject(document, object, message);
    }
}

PyObject* reorderTimelineOperationBlocks(Document* document, PyObject* args, const bool insertBefore)
{
    PyObject* pyOperations = nullptr;
    PyObject* pyTarget = nullptr;
    if (!PyArg_ParseTuple(args, "OO", &pyOperations, &pyTarget)) {
        return nullptr;
    }
    if (!PySequence_Check(pyOperations) || !PyObject_TypeCheck(pyTarget, &DocumentObjectPy::Type)) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected a sequence of document objects and one target document object"
        );
        return nullptr;
    }

    PY_TRY
    {
        Py::Object sequence
            = snapshotPythonSequence(pyOperations, "Timeline reorder inputs must be a sequence");
        const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
        PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
        std::vector<DocumentObject*> operations;
        operations.reserve(sequenceSize);
        for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
            if (!PyObject_TypeCheck(sequenceItems[index], &DocumentObjectPy::Type)) {
                throw Py::TypeError("Every timeline reorder input must be a document object");
            }
            auto* operation
                = static_cast<DocumentObjectPy*>(sequenceItems[index])->getDocumentObjectPtr();
            if (!operation || !document->containsObject(operation)
                || operation->getDocument() != document) {
                throw Py::ValueError("Every timeline reorder input must belong to this document");
            }
            operations.push_back(operation);
        }

        auto* target = static_cast<DocumentObjectPy*>(pyTarget)->getDocumentObjectPtr();
        if (!target || !document->containsObject(target) || target->getDocument() != document) {
            throw Py::ValueError("The timeline reorder target must belong to this document");
        }
        validateParsedDocumentObjects(
            document,
            operations,
            "A timeline reorder input was deleted while its sequence was parsed"
        );
        auto* timeline = DocumentTimeline::get(document);
        if (!timeline) {
            throw Py::RuntimeError("This document has no native operation timeline");
        }
        return Py::new_reference_to(Py::Boolean(
            insertBefore ? timeline->reorderOperationBlocksBefore(operations, target)
                         : timeline->reorderOperationBlocksAfter(operations, target)
        ));
    }
    PY_CATCH;
}

}  // namespace


PyObject* DocumentPy::addProperty(PyObject* args, PyObject* kwd)
{
    char* sType {nullptr};
    char* sName {nullptr};
    char* sGroup {nullptr};
    char* sDoc {nullptr};
    short attr = 0;
    std::string sDocStr;
    PyObject *ro = Py_False, *hd = Py_False, *lk = Py_False;
    PyObject* enumVals = nullptr;
    static const std::array<const char*, 10> kwlist {
        "type",
        "name",
        "group",
        "doc",
        "attr",
        "read_only",
        "hidden",
        "locked",
        "enum_vals",
        nullptr
    };
    if (!Base::Wrapped_ParseTupleAndKeywords(
            args,
            kwd,
            "ss|sethO!O!O!O",
            kwlist,
            &sType,
            &sName,
            &sGroup,
            "utf-8",
            &sDoc,
            &attr,
            &PyBool_Type,
            &ro,
            &PyBool_Type,
            &hd,
            &PyBool_Type,
            &lk,
            &enumVals
        )) {
        return nullptr;
    }

    if (sDoc) {
        sDocStr = sDoc;
        PyMem_Free(sDoc);
    }

    Property* prop = getDocumentPtr()->addDynamicProperty(
        sType,
        sName,
        sGroup,
        sDocStr.c_str(),
        attr,
        Base::asBoolean(ro),
        Base::asBoolean(hd)
    );
    prop->setStatus(Property::LockDynamic, Base::asBoolean(lk));

    // enum support
    auto* propEnum = dynamic_cast<App::PropertyEnumeration*>(prop);
    if (propEnum && enumVals) {
        propEnum->setPyObject(enumVals);
    }

    return Py::new_reference_to(this);
}

PyObject* DocumentPy::removeProperty(PyObject* args)
{
    char* sName;
    if (!PyArg_ParseTuple(args, "s", &sName)) {
        return nullptr;
    }

    bool ok = getDocumentPtr()->removeDynamicProperty(sName);
    return Py_BuildValue("O", (ok ? Py_True : Py_False));
}

// returns a string which represent the object e.g. when printed in python
std::string DocumentPy::representation() const
{
    std::stringstream str;
    str << "<Document '" << getDocumentPtr()->getName() << "' ("
        << getDocumentPtr()->Label.getValue() << ") >";

    return str.str();
}

PyObject* DocumentPy::save(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    PY_TRY
    {
        if (!getDocumentPtr()->save()) {
            PyErr_SetString(PyExc_ValueError, "Object attribute 'FileName' is not set");
            return nullptr;
        }
    }
    PY_CATCH;

    const char* filename = getDocumentPtr()->FileName.getValue();
    Base::FileInfo fi(filename);
    if (!fi.isReadable()) {
        PyErr_Format(PyExc_IOError, "No such file or directory: '%s'", filename);
        return nullptr;
    }

    Py_Return;
}

PyObject* DocumentPy::saveAs(PyObject* args)
{
    char* fn;
    if (!PyArg_ParseTuple(args, "et", "utf-8", &fn)) {
        return nullptr;
    }

    std::string utf8Name = fn;
    PyMem_Free(fn);

    PY_TRY
    {
        getDocumentPtr()->saveAs(utf8Name.c_str());
        Py_Return;
    }
    PY_CATCH
}

PyObject* DocumentPy::saveCopy(PyObject* args)
{
    char* fn;
    if (!PyArg_ParseTuple(args, "s", &fn)) {
        return nullptr;
    }

    PY_TRY
    {
        getDocumentPtr()->saveCopy(fn);
        Py_Return;
    }
    PY_CATCH
}

PyObject* DocumentPy::canWriteRecoverySnapshot(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    return Py::new_reference_to(Py::Boolean(getDocumentPtr()->canWriteRecoverySnapshot()));
}

PyObject* DocumentPy::load(PyObject* args)
{
    char* filename = nullptr;
    if (!PyArg_ParseTuple(args, "s", &filename)) {
        return nullptr;
    }
    if (!filename || *filename == '\0') {
        PyErr_Format(PyExc_ValueError, "Path is empty");
        return nullptr;
    }

    getDocumentPtr()->FileName.setValue(filename);
    Base::FileInfo fi(filename);
    if (!fi.isReadable()) {
        PyErr_Format(PyExc_IOError, "No such file or directory: '%s'", filename);
        return nullptr;
    }
    try {
        getDocumentPtr()->restore();
    }
    catch (...) {
        PyErr_Format(PyExc_IOError, "Reading from file '%s' failed", filename);
        return nullptr;
    }
    Py_Return;
}

PyObject* DocumentPy::restore(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const char* filename = getDocumentPtr()->FileName.getValue();
    if (!filename || *filename == '\0') {
        PyErr_Format(PyExc_ValueError, "Object attribute 'FileName' is not set");
        return nullptr;
    }
    Base::FileInfo fi(filename);
    if (!fi.isReadable()) {
        PyErr_Format(PyExc_IOError, "No such file or directory: '%s'", filename);
        return nullptr;
    }
    try {
        getDocumentPtr()->restore();
    }
    catch (...) {
        PyErr_Format(PyExc_IOError, "Reading from file '%s' failed", filename);
        return nullptr;
    }
    Py_Return;
}

PyObject* DocumentPy::isSaved(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isSaved();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::getProgramVersion(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const char* version = getDocumentPtr()->getProgramVersion();
    return Py::new_reference_to(Py::String(version));
}

PyObject* DocumentPy::getFileName(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    const char* fn = getDocumentPtr()->getFileName();
    return Py::new_reference_to(Py::String(fn));
}

PyObject* DocumentPy::getUniqueObjectName(PyObject* args)
{
    char* sName;
    if (!PyArg_ParseTuple(args, "s", &sName)) {
        return nullptr;
    }
    PY_TRY
    {
        auto newName = getDocumentPtr()->getUniqueObjectName(sName);
        return Py::new_reference_to(Py::String(newName));
    }
    PY_CATCH;
}

PyObject* DocumentPy::mergeProject(PyObject* args)
{
    char* filename;
    if (!PyArg_ParseTuple(args, "s", &filename)) {
        return nullptr;
    }

    PY_TRY
    {
        Base::FileInfo fi(filename);
        Base::ifstream str(fi, std::ios::in | std::ios::binary);
        App::Document* doc = getDocumentPtr();
        const bool ownsTransaction = doc->getBookedTransactionID() == App::NullTransaction;
        const int transactionId = ownsTransaction ? doc->openTransaction("Merge document")
                                                  : doc->getBookedTransactionID();
        try {
            DocumentTimeline::ensure(doc);
            MergeDocuments md(doc);
            auto imported = md.importObjects(str);
            str.close();
            doc->adoptImportedTimelineOperations(imported);
            if (ownsTransaction && !App::GetApplication().commitTransaction(transactionId)) {
                throw Base::RuntimeError("The merge transaction could not be committed");
            }
        }
        catch (...) {
            if (ownsTransaction && App::GetApplication().transactionIsActive(transactionId)) {
                App::GetApplication().abortTransaction(transactionId);
            }
            throw;
        }
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::exportGraphviz(PyObject* args)
{
    char* fn = nullptr;
    if (!PyArg_ParseTuple(args, "|s", &fn)) {
        return nullptr;
    }
    if (fn) {
        Base::FileInfo fi(fn);
        Base::ofstream str(fi);
        getDocumentPtr()->exportGraphviz(str);
        str.close();
        Py_Return;
    }
    else {
        std::stringstream str;
        getDocumentPtr()->exportGraphviz(str);
        return PyUnicode_FromString(str.str().c_str());
    }
}

PyObject* DocumentPy::addObject(PyObject* args, PyObject* kwd)
{
    char *sType, *sName = nullptr, *sViewType = nullptr;
    PyObject* obj = nullptr;
    PyObject* view = nullptr;
    PyObject* attach = Py_False;
    static const std::array<const char*, 7>
        kwlist {"type", "name", "objProxy", "viewProxy", "attach", "viewType", nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(
            args,
            kwd,
            "s|sOOO!s",
            kwlist,
            &sType,
            &sName,
            &obj,
            &view,
            &PyBool_Type,
            &attach,
            &sViewType
        )) {
        return nullptr;
    }

    DocumentObject* pcFtr = nullptr;

    if (!obj || !Base::asBoolean(attach)) {
        pcFtr = getDocumentPtr()->addObject(sType, sName, true, sViewType);
    }
    else {
        Base::Type type
            = Base::Type::getTypeIfDerivedFrom(sType, DocumentObject::getClassTypeId(), true);
        if (type.isBad()) {
            std::stringstream str;
            str << "'" << sType << "' is not a document object type";
            throw Base::TypeError(str.str());
        }
        pcFtr = static_cast<DocumentObject*>(type.createInstance());
    }
    // the type instance could be a null pointer
    if (!pcFtr) {
        std::stringstream str;
        str << "No document object found of type '" << sType << "'" << std::ends;
        throw Py::TypeError(str.str());
    }
    // Allows one to hide the handling with Proxy in client python code
    if (obj) {
        try {
            // the python binding class to the document object
            Py::Object pyftr = Py::asObject(pcFtr->getPyObject());
            // 'pyobj' is the python class with the implementation for DocumentObject
            Py::Object pyobj(obj);
            if (pyobj.hasAttr("__object__")) {
                pyobj.setAttr("__object__", pyftr);
            }
            pyftr.setAttr("Proxy", pyobj);

            if (Base::asBoolean(attach)) {
                getDocumentPtr()->addObject(pcFtr, sName);

                try {
                    Py::Callable method(pyobj.getAttr("attach"));
                    if (!method.isNone()) {
                        Py::TupleN arg(pyftr);
                        method.apply(arg);
                    }
                }
                catch (Py::Exception&) {
                    Base::PyException e;
                    e.reportException();
                }
            }

            // if a document class is set we also need a view provider defined which must be
            // something different to None
            Py::Object pyvp;
            if (view) {
                pyvp = Py::Object(view);
            }
            if (pyvp.isNone()) {
                pyvp = Py::Long(1);
            }
            // 'pyvp' is the python class with the implementation for ViewProvider
            if (pyvp.hasAttr("__vobject__")) {
                pyvp.setAttr("__vobject__", pyftr.getAttr("ViewObject"));
            }

            Py::Object pyprx(pyftr.getAttr("ViewObject"));
            pyprx.setAttr("Proxy", pyvp);
            return Py::new_reference_to(pyftr);
        }
        catch (Py::Exception& e) {
            e.clear();
        }
    }
    return pcFtr->getPyObject();
}

PyObject* DocumentPy::removeObject(PyObject* args)
{
    char* sName {};
    if (PyArg_ParseTuple(args, "s", &sName)) {
        DocumentObject* object = getDocumentPtr()->getObject(sName);
        if (object) {
            getDocumentPtr()->removeObject(sName);
            Py_Return;
        }

        std::stringstream str;
        str << "No document object found with name '" << sName << "'" << std::ends;
        throw Py::ValueError(str.str());
    }

    PyErr_Clear();
    PyObject* objpy {};
    if (PyArg_ParseTuple(args, "O!", &App::DocumentObjectPy::Type, &objpy)) {
        DocumentObject* object = static_cast<App::DocumentObjectPy*>(objpy)->getDocumentObjectPtr();
        if (!object) {
            PyErr_Format(PyExc_RuntimeError, "Invalid document object");
            return nullptr;
        }

        if (object->getDocument() == getDocumentPtr()) {
            getDocumentPtr()->removeObject(object);
            Py_Return;
        }

        std::stringstream str;
        str << "Document object is not part of this document";
        throw Py::ValueError(str.str());
    }

    PyErr_SetString(PyExc_TypeError, "Expect str or DocumentObject");
    return nullptr;
}

PyObject* DocumentPy::copyObject(PyObject* args, PyObject* kwd)
{
    PyObject* obj;
    PyObject* rec = Py_False;
    PyObject* retAll = Py_False;
    static constexpr std::array<const char*, 4> kwlist {"object", "recursive", "return_all", nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(
            args,
            kwd,
            "O|O!O!",
            kwlist,
            &obj,
            &PyBool_Type,
            &rec,
            &PyBool_Type,
            &retAll
        )) {
        return nullptr;
    }

    std::vector<App::DocumentObject*> objs;
    bool single = false;
    if (PySequence_Check(obj)) {
        Py::Sequence seq(obj);
        for (Py_ssize_t i = 0; i < seq.size(); ++i) {
            if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                PyErr_SetString(
                    PyExc_TypeError,
                    "Expect element in sequence to be of type document object"
                );
                return nullptr;
            }
            objs.push_back(static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
        }
    }
    else if (!PyObject_TypeCheck(obj, &DocumentObjectPy::Type)) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expect first argument to be either a document object or sequence of document objects"
        );
        return nullptr;
    }
    else {
        objs.push_back(static_cast<DocumentObjectPy*>(obj)->getDocumentObjectPtr());
        single = true;
    }

    PY_TRY
    {
        auto ret = getDocumentPtr()->copyObject(objs, Base::asBoolean(rec), Base::asBoolean(retAll));
        if (ret.size() == 1 && single) {
            return ret[0]->getPyObject();
        }

        Py::Tuple tuple(ret.size());
        for (size_t i = 0; i < ret.size(); ++i) {
            tuple.setItem(i, Py::Object(ret[i]->getPyObject(), true));
        }
        return Py::new_reference_to(tuple);
    }
    PY_CATCH
}

PyObject* DocumentPy::importLinks(PyObject* args)
{
    PyObject* obj = Py_None;
    if (!PyArg_ParseTuple(args, "|O", &obj)) {
        return nullptr;
    }

    std::vector<App::DocumentObject*> objs;
    if (PySequence_Check(obj)) {
        Py::Sequence seq(obj);
        for (Py_ssize_t i = 0; i < seq.size(); ++i) {
            if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                PyErr_SetString(
                    PyExc_TypeError,
                    "Expect element in sequence to be of type document object"
                );
                return nullptr;
            }
            objs.push_back(static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
        }
    }
    else {
        Base::PyTypeCheck(
            &obj,
            &DocumentObjectPy::Type,
            "Expect first argument to be either a document object, sequence of "
            "document objects or None"
        );
        if (obj) {
            objs.push_back(static_cast<DocumentObjectPy*>(obj)->getDocumentObjectPtr());
        }
    }

    if (objs.empty()) {
        objs = getDocumentPtr()->getObjects();
    }

    PY_TRY
    {
        auto ret = getDocumentPtr()->importLinks(objs);

        Py::Tuple tuple(ret.size());
        for (size_t i = 0; i < ret.size(); ++i) {
            tuple.setItem(i, Py::Object(ret[i]->getPyObject(), true));
        }
        return Py::new_reference_to(tuple);
    }
    PY_CATCH
}

PyObject* DocumentPy::moveObject(PyObject* args)
{
    PyObject *obj, *rec = Py_False;
    if (!PyArg_ParseTuple(args, "O!|O!", &(DocumentObjectPy::Type), &obj, &PyBool_Type, &rec)) {
        return nullptr;
    }

    DocumentObjectPy* docObj = static_cast<DocumentObjectPy*>(obj);
    DocumentObject* move
        = getDocumentPtr()->moveObject(docObj->getDocumentObjectPtr(), Base::asBoolean(rec));
    if (move) {
        return move->getPyObject();
    }
    else {
        std::string str("Failed to move the object");
        throw Py::ValueError(str);
    }
}

PyObject* DocumentPy::openTransaction(PyObject* args)
{
    PyObject* value = nullptr;
    if (!PyArg_ParseTuple(args, "|O", &value)) {
        return nullptr;
    }
    std::string cmd;


    if (!value) {
        cmd = "<empty>";
    }
    else if (PyUnicode_Check(value)) {
        cmd = PyUnicode_AsUTF8(value);
    }
    else {
        PyErr_SetString(PyExc_TypeError, "string or unicode expected");
        return nullptr;
    }

    getDocumentPtr()->openTransaction(cmd.c_str());
    Py_Return;
}

PyObject* DocumentPy::abortTransaction(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->abortTransaction();
    Py_Return;
}

PyObject* DocumentPy::commitTransaction(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->commitTransaction();
    Py_Return;
}

Py::Boolean DocumentPy::getHasPendingTransaction() const
{
    return {getDocumentPtr()->hasPendingTransaction()};
}

PyObject* DocumentPy::undo(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    if (getDocumentPtr()->getAvailableUndos()) {
        getDocumentPtr()->undo();
    }
    Py_Return;
}

PyObject* DocumentPy::redo(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    if (getDocumentPtr()->getAvailableRedos()) {
        getDocumentPtr()->redo();
    }
    Py_Return;
}

PyObject* DocumentPy::clearUndos(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->clearUndos();
    Py_Return;
}

PyObject* DocumentPy::clearDocument(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->clearDocument();
    Py_Return;
}

PyObject* DocumentPy::setClosable(PyObject* args)
{
    PyObject* close;
    if (!PyArg_ParseTuple(args, "O!", &PyBool_Type, &close)) {
        return nullptr;
    }
    getDocumentPtr()->setClosable(Base::asBoolean(close));
    Py_Return;
}

PyObject* DocumentPy::isClosable(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isClosable();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::setAutoCreated(PyObject* args)
{
    PyObject* autoCreated;
    if (!PyArg_ParseTuple(args, "O!", &PyBool_Type, &autoCreated)) {
        return nullptr;
    }
    bool value = (autoCreated == Py_True);
    getDocumentPtr()->setAutoCreated(value);

    Py_RETURN_NONE;
}

PyObject* DocumentPy::isAutoCreated(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isAutoCreated();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::recompute(PyObject* args)
{
    PyObject* pyobjs = Py_None;
    PyObject* force = Py_False;
    PyObject* checkCycle = Py_False;
    if (!PyArg_ParseTuple(args, "|OO!O!", &pyobjs, &PyBool_Type, &force, &PyBool_Type, &checkCycle)) {
        return nullptr;
    }

    PY_TRY
    {
        std::vector<App::DocumentObject*> objs;
        if (pyobjs != Py_None) {
            if (!PySequence_Check(pyobjs)) {
                PyErr_SetString(PyExc_TypeError, "expect input of sequence of document objects");
                return nullptr;
            }

            Py::Sequence seq(pyobjs);
            for (Py_ssize_t i = 0; i < seq.size(); ++i) {
                if (!PyObject_TypeCheck(seq[i].ptr(), &DocumentObjectPy::Type)) {
                    PyErr_SetString(
                        PyExc_TypeError,
                        "Expect element in sequence to be of type document object"
                    );
                    return nullptr;
                }
                objs.push_back(static_cast<DocumentObjectPy*>(seq[i].ptr())->getDocumentObjectPtr());
            }
        }

        int options = 0;
        if (Base::asBoolean(checkCycle)) {
            options = Document::DepNoCycle;
        }

        int objectCount = getDocumentPtr()->recompute(objs, Base::asBoolean(force), nullptr, options);

        // Document::recompute() hides possibly raised Python exceptions by its features
        // So, check if an error is set and return null if yes
        if (PyErr_Occurred()) {
            return nullptr;
        }

        return Py::new_reference_to(Py::Long(objectCount));
    }
    PY_CATCH;
}

PyObject* DocumentPy::recomputeAsync(PyObject* args)
{
    PyObject* pyobjs = Py_None;
    PyObject* recursive = Py_False;
    if (!PyArg_ParseTuple(args, "|OO!", &pyobjs, &PyBool_Type, &recursive)) {
        return nullptr;
    }

    PY_TRY
    {
        Document* document = getDocumentPtr();
        std::vector<RecomputeRequest> requests;
        if (pyobjs == Py_None) {
            requests.push_back(RecomputeRequest::fromDocument(*document));
        }
        else {
            if (!PySequence_Check(pyobjs)) {
                PyErr_SetString(PyExc_TypeError, "expect input of sequence of document objects");
                return nullptr;
            }
            Py::Sequence sequence(pyobjs);
            requests.reserve(sequence.size());
            for (Py_ssize_t index = 0; index < sequence.size(); ++index) {
                if (!PyObject_TypeCheck(sequence[index].ptr(), &DocumentObjectPy::Type)) {
                    PyErr_SetString(
                        PyExc_TypeError,
                        "Expect element in sequence to be of type document object"
                    );
                    return nullptr;
                }
                auto* object
                    = static_cast<DocumentObjectPy*>(sequence[index].ptr())->getDocumentObjectPtr();
                if (!object || object->getDocument() != document) {
                    PyErr_SetString(
                        PyExc_ValueError,
                        "Every asynchronous recompute object must belong to this document"
                    );
                    return nullptr;
                }
                requests.push_back(
                    RecomputeRequest::fromDocumentObject(*object, Base::asBoolean(recursive))
                );
            }
        }

        Application& application = GetApplication();
        std::vector<std::string> unsafeObjects;
        for (const auto& request : requests) {
            if (!application.canRecomputeRequestOnWorker(request)) {
                unsafeObjects.push_back(
                    request.documentObjectName.empty() ? std::string("<document>")
                                                       : request.documentObjectName
                );
            }
        }
        if (!unsafeObjects.empty()) {
            std::ostringstream message;
            message << "Asynchronous recompute rejected thread-affine target";
            if (unsafeObjects.size() != 1) {
                message << 's';
            }
            message << ": ";
            for (std::size_t index = 0; index < unsafeObjects.size(); ++index) {
                if (index != 0) {
                    message << ", ";
                }
                message << unsafeObjects[index];
            }
            throw Base::RuntimeError(message.str());
        }

        const auto requestCount = requests.size();
        if (!application.tryQueueRecomputeRequests(std::move(requests))) {
            throw Base::RuntimeError(
                "Asynchronous recompute targets became worker-unsafe before they were queued"
            );
        }
        return Py::new_reference_to(Py::Long(requestCount));
    }
    PY_CATCH;
}

PyObject* DocumentPy::getRecomputeDiagnostics(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    const auto* document = getDocumentPtr();
    PyObject* result = PyDict_New();
    PyObject* generation = PyLong_FromUnsignedLongLong(document->getRecomputeDiagnosticGeneration());
    PyDict_SetItemString(result, "generation", generation);
    Py_DECREF(generation);

    const auto& diagnostics = document->getRecomputeDiagnostics();
    PyObject* entries = PyList_New(static_cast<Py_ssize_t>(diagnostics.size()));
    for (std::size_t index = 0; index < diagnostics.size(); ++index) {
        const auto& diagnostic = diagnostics[index];
        PyObject* entry = PyDict_New();
        auto setString = [entry](const char* key, const std::string& value) {
            PyObject* pyValue = PyUnicode_FromString(value.c_str());
            PyDict_SetItemString(entry, key, pyValue);
            Py_DECREF(pyValue);
        };
        PyObject* itemGeneration = PyLong_FromUnsignedLongLong(diagnostic.generation);
        PyDict_SetItemString(entry, "generation", itemGeneration);
        Py_DECREF(itemGeneration);
        setString("severity", diagnostic.severity);
        setString("code", diagnostic.code);
        setString("object", diagnostic.object);
        setString("property", diagnostic.property);
        setString("subelement", diagnostic.subelement);
        setString("algorithm", diagnostic.algorithm);
        setString("message", diagnostic.message);
        PyList_SET_ITEM(entries, static_cast<Py_ssize_t>(index), entry);
    }
    PyDict_SetItemString(result, "diagnostics", entries);
    Py_DECREF(entries);
    return result;
}

PyObject* DocumentPy::mustExecute(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->mustExecute();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::isTouched(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    bool ok = getDocumentPtr()->isTouched();
    return Py::new_reference_to(Py::Boolean(ok));
}

PyObject* DocumentPy::purgeTouched(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    getDocumentPtr()->purgeTouched();
    Py_Return;
}

PyObject* DocumentPy::getObject(PyObject* args)
{
    DocumentObject* obj = nullptr;

    do {
        char* name = nullptr;
        if (PyArg_ParseTuple(args, "s", &name)) {
            obj = getDocumentPtr()->getObject(name);
            break;
        }

        PyErr_Clear();
        long id = -1;
        if (PyArg_ParseTuple(args, "l", &id)) {
            obj = getDocumentPtr()->getObjectByID(id);
            break;
        }

        PyErr_SetString(PyExc_TypeError, "a string or integer is required");
        return nullptr;
    } while (false);

    if (obj) {
        return obj->getPyObject();
    }

    Py_Return;
}

PyObject* DocumentPy::getObjectsByLabel(PyObject* args)
{
    char* sName;
    if (!PyArg_ParseTuple(args, "s", &sName)) {
        return nullptr;
    }

    Py::List list;
    std::string name = sName;
    std::vector<DocumentObject*> objs = getDocumentPtr()->getObjects();
    for (auto obj : objs) {
        if (name == obj->Label.getValue()) {
            list.append(Py::asObject(obj->getPyObject()));
        }
    }

    return Py::new_reference_to(list);
}

PyObject* DocumentPy::findObjects(PyObject* args, PyObject* kwds)
{
    const char *sType = "App::DocumentObject", *sName = nullptr, *sLabel = nullptr;
    static const std::array<const char*, 4> kwlist {"Type", "Name", "Label", nullptr};
    if (!Base::Wrapped_ParseTupleAndKeywords(args, kwds, "|sss", kwlist, &sType, &sName, &sLabel)) {
        return nullptr;
    }

    Base::Type type
        = Base::Type::getTypeIfDerivedFrom(sType, App::DocumentObject::getClassTypeId(), true);
    if (type.isBad()) {
        std::stringstream str;
        str << "'" << sType << "' is not a document object type";
        throw Base::TypeError(str.str());
    }

    std::vector<DocumentObject*> res;

    try {
        res = getDocumentPtr()->findObjects(type, sName, sLabel);
    }
    catch (const boost::regex_error& e) {
        PyErr_SetString(PyExc_RuntimeError, e.what());
        return nullptr;
    }

    Py_ssize_t index = 0;
    PyObject* list = PyList_New((Py_ssize_t)res.size());
    for (std::vector<DocumentObject*>::const_iterator It = res.begin(); It != res.end();
         ++It, index++) {
        PyList_SetItem(list, index, (*It)->getPyObject());
    }
    return list;
}

Py::Object DocumentPy::getActiveObject() const
{
    DocumentObject* pcFtr = getDocumentPtr()->getActiveObject();
    if (pcFtr) {
        return Py::Object(pcFtr->getPyObject(), true);
    }
    return Py::None();
}

PyObject* DocumentPy::supportedTypes(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    std::vector<Base::Type> ary;
    Base::Type::getAllDerivedFrom(App::DocumentObject::getClassTypeId(), ary);
    Py::List res;
    for (const auto& it : ary) {
        res.append(Base::toPyString(it.getName()));
    }
    return Py::new_reference_to(res);
}

Py::List DocumentPy::getObjects() const
{
    std::vector<DocumentObject*> objs = getDocumentPtr()->getObjects();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::List DocumentPy::getTopologicalSortedObjects() const
{
    std::vector<DocumentObject*> objs = getDocumentPtr()->topologicalSort();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::List DocumentPy::getRootObjects() const
{
    std::vector<DocumentObject*> objs = getDocumentPtr()->getRootObjects();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::List DocumentPy::getRootObjectsIgnoreLinks() const
{
    std::vector<App::DocumentObject*> objs = getDocumentPtr()->getRootObjectsIgnoreLinks();
    Py::List res;

    for (auto obj : objs) {
        // Note: Here we must force the Py::Object to own this Python object as getPyObject()
        // increments the counter
        res.append(Py::Object(obj->getPyObject(), true));
    }

    return res;
}

Py::Long DocumentPy::getUndoMode() const
{
    return Py::Long(getDocumentPtr()->getUndoMode());
}

void DocumentPy::setUndoMode(Py::Long arg)
{
    getDocumentPtr()->setUndoMode(arg);
}


Py::Long DocumentPy::getUndoRedoMemSize() const
{
    return Py::Long((long)getDocumentPtr()->getUndoMemSize());
}

Py::Long DocumentPy::getUndoCount() const
{
    return Py::Long((long)getDocumentPtr()->getAvailableUndos());
}

Py::Long DocumentPy::getRedoCount() const
{
    return Py::Long((long)getDocumentPtr()->getAvailableRedos());
}

Py::List DocumentPy::getUndoNames() const
{
    std::vector<std::string> vList = getDocumentPtr()->getAvailableUndoNames();
    Py::List res;

    for (const auto& It : vList) {
        res.append(Py::String(It));
    }

    return res;
}

Py::List DocumentPy::getRedoNames() const
{
    std::vector<std::string> vList = getDocumentPtr()->getAvailableRedoNames();
    Py::List res;

    for (const auto& It : vList) {
        res.append(Py::String(It));
    }

    return res;
}

Py::String DocumentPy::getDependencyGraph() const
{
    std::stringstream out;
    getDocumentPtr()->exportGraphviz(out);
    return {out.str()};
}

Py::String DocumentPy::getName() const
{
    return {getDocumentPtr()->getName()};
}

Py::Boolean DocumentPy::getRecomputesFrozen() const
{
    return {getDocumentPtr()->testStatus(Document::Status::SkipRecompute)};
}

void DocumentPy::setRecomputesFrozen(Py::Boolean arg)
{
    getDocumentPtr()->setStatus(Document::Status::SkipRecompute, arg.isTrue());
}

PyObject* DocumentPy::getTempFileName(PyObject* args)
{
    PyObject* value;
    if (!PyArg_ParseTuple(args, "O", &value)) {
        return nullptr;
    }

    std::string string;
    if (PyUnicode_Check(value)) {
        string = PyUnicode_AsUTF8(value);
    }
    else {
        std::string error = std::string("type must be a string!");
        error += value->ob_type->tp_name;
        throw Py::TypeError(error);
    }

    // search for a temp file name in the document transient directory
    Base::FileInfo fileName(
        Base::FileInfo::getTempFileName(string.c_str(), getDocumentPtr()->TransientDir.getValue())
    );
    // delete the created file, we need only the name...
    fileName.deleteFile();

    PyObject* p
        = PyUnicode_DecodeUTF8(fileName.filePath().c_str(), fileName.filePath().size(), nullptr);
    if (!p) {
        throw Base::UnicodeError("UTF8 conversion failure at PropertyString::getPyObject()");
    }
    return p;
}

PyObject* DocumentPy::getCustomAttributes(const char* attr) const
{
    // Note: Here we want to return only a document object if its
    // name matches 'attr'. However, it is possible to have an object
    // with the same name as an attribute. If so, we return 0 as other-
    // wise it wouldn't be possible to address this attribute any more.
    // The object must then be addressed by the getObject() method directly.
    App::Property* prop = getPropertyContainerPtr()->getPropertyByName(attr);
    if (prop) {
        return nullptr;
    }
    if (!this->ob_type->tp_dict) {
        if (PyType_Ready(this->ob_type) < 0) {
            return nullptr;
        }
    }
    PyObject* item = PyDict_GetItemString(this->ob_type->tp_dict, attr);
    if (item) {
        return nullptr;
    }
    // search for an object with this name
    DocumentObject* obj = getDocumentPtr()->getObject(attr);
    return (obj ? obj->getPyObject() : nullptr);
}

int DocumentPy::setCustomAttributes(const char* attr, PyObject*)
{
    // Note: Here we want to return only a document object if its
    // name matches 'attr'. However, it is possible to have an object
    // with the same name as an attribute. If so, we return 0 as other-
    // wise it wouldn't be possible to address this attribute any more.
    // The object must then be addressed by the getObject() method directly.
    App::Property* prop = getPropertyContainerPtr()->getPropertyByName(attr);
    if (prop) {
        return 0;
    }
    if (!this->ob_type->tp_dict) {
        if (PyType_Ready(this->ob_type) < 0) {
            return 0;
        }
    }
    PyObject* item = PyDict_GetItemString(this->ob_type->tp_dict, attr);
    if (item) {
        return 0;
    }
    DocumentObject* obj = getDocumentPtr()->getObject(attr);
    if (obj) {
        std::stringstream str;
        str << "'Document' object attribute '" << attr << "' must not be set this way" << std::ends;
        PyErr_SetString(PyExc_RuntimeError, str.str().c_str());
        return -1;
    }

    return 0;
}

PyObject* DocumentPy::getLinksTo(PyObject* args)
{
    PyObject* pyobj = Py_None;
    int options = 0;
    short count = 0;
    if (!PyArg_ParseTuple(args, "|Oih", &pyobj, &options, &count)) {
        return nullptr;
    }

    PY_TRY
    {
        Base::PyTypeCheck(
            &pyobj,
            &DocumentObjectPy::Type,
            "Expect the first argument of type document object"
        );
        DocumentObject* obj = nullptr;
        if (pyobj) {
            obj = static_cast<DocumentObjectPy*>(pyobj)->getDocumentObjectPtr();
        }

        std::set<DocumentObject*> links;
        getDocumentPtr()->getLinksTo(links, obj, options, count);
        Py::Tuple ret(links.size());
        int i = 0;
        for (auto o : links) {
            ret.setItem(i++, Py::Object(o->getPyObject(), true));
        }

        return Py::new_reference_to(ret);
    }
    PY_CATCH
}

Py::List DocumentPy::getInList() const
{
    Py::List ret;
    auto lists = PropertyXLink::getDocumentInList(getDocumentPtr());
    if (lists.size() == 1) {
        for (auto doc : lists.begin()->second) {
            ret.append(Py::Object(doc->getPyObject(), true));
        }
    }
    return ret;
}

Py::List DocumentPy::getOutList() const
{
    Py::List ret;
    auto lists = PropertyXLink::getDocumentOutList(getDocumentPtr());
    if (lists.size() == 1) {
        for (auto doc : lists.begin()->second) {
            ret.append(Py::Object(doc->getPyObject(), true));
        }
    }
    return ret;
}

PyObject* DocumentPy::getDependentDocuments(PyObject* args)
{
    PyObject* sort = Py_True;
    if (!PyArg_ParseTuple(args, "|O!", &PyBool_Type, &sort)) {
        return nullptr;
    }
    PY_TRY
    {
        auto docs = getDocumentPtr()->getDependentDocuments(Base::asBoolean(sort));
        Py::List ret;
        for (auto doc : docs) {
            ret.append(Py::Object(doc->getPyObject(), true));
        }
        return Py::new_reference_to(ret);
    }
    PY_CATCH;
}
PyObject* DocumentPy::getBookedTransactionID(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }
    int tid = getDocumentPtr()->getBookedTransactionID();
    return Py::new_reference_to(Py::Long(tid));
}

PyObject* DocumentPy::reorderTimelineOperationBlocksAfter(PyObject* args)
{
    return reorderTimelineOperationBlocks(getDocumentPtr(), args, false);
}

PyObject* DocumentPy::reorderTimelineOperationBlocksBefore(PyObject* args)
{
    return reorderTimelineOperationBlocks(getDocumentPtr(), args, true);
}

PyObject* DocumentPy::reorderTimelineOperationDependentClosureAfter(PyObject* args)
{
    PyObject* pyOperation = nullptr;
    PyObject* pyTarget = nullptr;
    if (!PyArg_ParseTuple(args, "OO", &pyOperation, &pyTarget)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOperation, &DocumentObjectPy::Type)
        || !PyObject_TypeCheck(pyTarget, &DocumentObjectPy::Type)) {
        PyErr_SetString(PyExc_TypeError,
                       "Timeline dependency rebase inputs must be document objects");
        return nullptr;
    }

    auto* document = getDocumentPtr();
    auto* operation = static_cast<DocumentObjectPy*>(pyOperation)->getDocumentObjectPtr();
    auto* target = static_cast<DocumentObjectPy*>(pyTarget)->getDocumentObjectPtr();
    if (!operation || !target || !document->containsObject(operation)
        || !document->containsObject(target) || operation->getDocument() != document
        || target->getDocument() != document) {
        PyErr_SetString(PyExc_ValueError,
                       "Timeline dependency rebase inputs must belong to this document");
        return nullptr;
    }

    try {
        auto* timeline = DocumentTimeline::get(document);
        if (!timeline) {
            throw Py::RuntimeError("This document has no native operation timeline");
        }
        return Py::new_reference_to(
            Py::Boolean(timeline->reorderOperationDependentClosureAfter(operation, target)));
    }
    PY_CATCH;
}

PyObject* DocumentPy::adoptImportedTimelineOperations(PyObject* args)
{
    PyObject* pyObjects = nullptr;
    PyObject* pySourceOrder = nullptr;
    PyObject* pySourceVisibility = nullptr;
    PyObject* pySourceSuppression = nullptr;
    if (!PyArg_ParseTuple(
            args,
            "O|OOO",
            &pyObjects,
            &pySourceOrder,
            &pySourceVisibility,
            &pySourceSuppression
        )) {
        return nullptr;
    }
    if (!PySequence_Check(pyObjects) || (pySourceOrder && !PySequence_Check(pySourceOrder))
        || (pySourceVisibility && !PySequence_Check(pySourceVisibility))
        || (pySourceSuppression && !PySequence_Check(pySourceSuppression))) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected imported objects plus optional source-order, "
            "visibility, and suppression sequences"
        );
        return nullptr;
    }

    const auto parseObjects = [](PyObject* value, const char* description) {
        Py::Object sequence = snapshotPythonSequence(value, description);
        const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
        PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
        std::vector<DocumentObject*> objects;
        objects.reserve(sequenceSize);
        for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
            if (!PyObject_TypeCheck(sequenceItems[index], &DocumentObjectPy::Type)) {
                throw Py::TypeError(description);
            }
            objects.push_back(
                static_cast<DocumentObjectPy*>(sequenceItems[index])->getDocumentObjectPtr()
            );
        }
        return objects;
    };
    const auto parseStates = [](PyObject* value) {
        Py::Object sequence
            = snapshotPythonSequence(value, "Source timeline states must be a sequence");
        const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
        PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
        std::vector<bool> states;
        states.reserve(sequenceSize);
        for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
            if (!PyBool_Check(sequenceItems[index])) {
                throw Py::TypeError("Every source timeline state must be bool");
            }
            states.push_back(sequenceItems[index] == Py_True);
        }
        return states;
    };

    PY_TRY
    {
        auto imported
            = parseObjects(pyObjects, "Every imported timeline object must be a document object");
        std::vector<DocumentObject*> sourceOrder;
        if (pySourceOrder) {
            sourceOrder
                = parseObjects(pySourceOrder, "Every source-order item must be a document object");
        }
        std::vector<bool> sourceVisibility;
        if (pySourceVisibility) {
            sourceVisibility = parseStates(pySourceVisibility);
        }
        std::vector<bool> sourceSuppression;
        if (pySourceSuppression) {
            sourceSuppression = parseStates(pySourceSuppression);
        }
        auto* document = getDocumentPtr();
        validateParsedDocumentObjects(
            document,
            imported,
            "An imported timeline object was deleted while import sequences were parsed"
        );
        validateParsedDocumentObjects(
            document,
            sourceOrder,
            "A source-order object was deleted while import sequences were parsed"
        );
        document->adoptImportedTimelineOperations(
            imported,
            sourceOrder,
            sourceVisibility,
            sourceSuppression
        );
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::finalizeProvisionalTimelineOperationBlock(PyObject* args)
{
    PyObject* pyOperation = nullptr;
    PyObject* pyOrderedNewObjects = nullptr;
    if (!PyArg_ParseTuple(args, "OO", &pyOperation, &pyOrderedNewObjects)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOperation, &DocumentObjectPy::Type)
        || !PySequence_Check(pyOrderedNewObjects)) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected one operation and a sequence of newly enrolled "
            "document objects"
        );
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* operation = static_cast<DocumentObjectPy*>(pyOperation)->getDocumentObjectPtr();
        if (!operation || !document->containsObject(operation)
            || operation->getDocument() != document) {
            throw Py::ValueError(
                "The provisional block operation must be live in this "
                "document"
            );
        }

        Py::Object sequence = snapshotPythonSequence(
            pyOrderedNewObjects,
            "Provisional block items must be a sequence"
        );
        const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
        PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
        std::vector<DocumentObject*> orderedNewObjects;
        orderedNewObjects.reserve(sequenceSize);
        for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
            if (!PyObject_TypeCheck(sequenceItems[index], &DocumentObjectPy::Type)) {
                throw Py::TypeError("Every provisional block item must be a document object");
            }
            auto* candidate
                = static_cast<DocumentObjectPy*>(sequenceItems[index])->getDocumentObjectPtr();
            if (!candidate || !document->containsObject(candidate)
                || candidate->getDocument() != document) {
                throw Py::ValueError(
                    "Every provisional block item must be live in this "
                    "document"
                );
            }
            orderedNewObjects.push_back(candidate);
        }

        validateParsedDocumentObject(
            document,
            operation,
            "The provisional block operation was deleted while its sequence was parsed"
        );
        validateParsedDocumentObjects(
            document,
            orderedNewObjects,
            "A provisional block item was deleted while its sequence was parsed"
        );
        auto* timeline = DocumentTimeline::get(document);
        if (!timeline) {
            throw Py::RuntimeError("This document has no native operation timeline");
        }
        timeline->finalizeProvisionalOperationBlock(operation, orderedNewObjects);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::publishProvisionalTimelineOperationBlock(PyObject* args)
{
    PyObject* pyOperation = nullptr;
    PyObject* pyResources = nullptr;
    PyObject* pyOwners = nullptr;
    if (!PyArg_ParseTuple(args, "OO|O", &pyOperation, &pyResources, &pyOwners)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOperation, &DocumentObjectPy::Type) || !PySequence_Check(pyResources)
        || (pyOwners && !PySequence_Check(pyOwners))) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected one document operation, a resource sequence, and an "
            "optional parallel owner sequence"
        );
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* operation = static_cast<DocumentObjectPy*>(pyOperation)->getDocumentObjectPtr();
        if (!operation || !document->containsObject(operation)
            || operation->getDocument() != document) {
            throw Py::ValueError("The published operation must be live in this document");
        }

        const auto parseObjects = [document](PyObject* value, const char* memberDescription) {
            Py::Object sequence
                = snapshotPythonSequence(value, "Timeline publication members must be a sequence");
            const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
            PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
            std::vector<DocumentObject*> objects;
            objects.reserve(sequenceSize);
            for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
                if (!PyObject_TypeCheck(sequenceItems[index], &DocumentObjectPy::Type)) {
                    throw Py::TypeError(
                        std::string("Every ") + memberDescription + " must be a document object"
                    );
                }
                auto* object
                    = static_cast<DocumentObjectPy*>(sequenceItems[index])->getDocumentObjectPtr();
                if (!object || !document->containsObject(object)
                    || object->getDocument() != document) {
                    throw Py::ValueError(
                        std::string("Every ") + memberDescription + " must be live in this document"
                    );
                }
                objects.push_back(object);
            }
            return objects;
        };
        auto resources = parseObjects(pyResources, "published resource");
        std::vector<DocumentObject*> owners;
        if (pyOwners) {
            owners = parseObjects(pyOwners, "resource owner");
        }
        validateParsedDocumentObject(
            document,
            operation,
            "The published operation was deleted while publication sequences were parsed"
        );
        validateParsedDocumentObjects(
            document,
            resources,
            "A published resource was deleted while publication sequences were parsed"
        );
        validateParsedDocumentObjects(
            document,
            owners,
            "A resource owner was deleted while publication sequences were parsed"
        );
        document->publishProvisionalTimelineOperationBlock(operation, resources, owners);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::adoptExistingTimelineOperationBlock(PyObject* args)
{
    PyObject* pyOperation = nullptr;
    PyObject* pyResources = nullptr;
    PyObject* pyOwners = nullptr;
    if (!PyArg_ParseTuple(args, "OO|O", &pyOperation, &pyResources, &pyOwners)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOperation, &DocumentObjectPy::Type) || !PySequence_Check(pyResources)
        || (pyOwners && !PySequence_Check(pyOwners))) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected one document operation, a resource sequence, and an "
            "optional parallel owner sequence"
        );
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* operation = static_cast<DocumentObjectPy*>(pyOperation)->getDocumentObjectPtr();
        if (!operation || !document->containsObject(operation)
            || operation->getDocument() != document) {
            throw Py::ValueError("The adopted operation must be live in this document");
        }

        const auto parseObjects = [document](PyObject* value, const char* description) {
            Py::Object sequence
                = snapshotPythonSequence(value, "Timeline adoption members must be a sequence");
            const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
            PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
            std::vector<DocumentObject*> objects;
            objects.reserve(sequenceSize);
            for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
                if (!PyObject_TypeCheck(sequenceItems[index], &DocumentObjectPy::Type)) {
                    throw Py::TypeError(
                        std::string("Every ") + description + " must be a document object"
                    );
                }
                auto* object
                    = static_cast<DocumentObjectPy*>(sequenceItems[index])->getDocumentObjectPtr();
                if (!object || !document->containsObject(object)
                    || object->getDocument() != document) {
                    throw Py::ValueError(
                        std::string("Every ") + description + " must be live in this document"
                    );
                }
                objects.push_back(object);
            }
            return objects;
        };

        auto resources = parseObjects(pyResources, "adopted resource");
        std::vector<DocumentObject*> owners;
        if (pyOwners) {
            owners = parseObjects(pyOwners, "adopted resource owner");
        }
        validateParsedDocumentObject(
            document,
            operation,
            "The adopted operation was deleted while adoption sequences were parsed"
        );
        validateParsedDocumentObjects(
            document,
            resources,
            "An adopted resource was deleted while adoption sequences were parsed"
        );
        validateParsedDocumentObjects(
            document,
            owners,
            "An adopted resource owner was deleted while adoption sequences were parsed"
        );
        document->adoptExistingTimelineOperationBlock(operation, resources, owners);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::classifyProvisionalTimelineInternalObject(PyObject* args)
{
    PyObject* pyObject = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyObject)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyObject, &DocumentObjectPy::Type)) {
        PyErr_SetString(PyExc_TypeError, "Expected one document object");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* object = static_cast<DocumentObjectPy*>(pyObject)->getDocumentObjectPtr();
        if (!object || !document->containsObject(object) || object->getDocument() != document) {
            throw Py::ValueError("The internal object must be live in this document");
        }
        document->classifyProvisionalTimelineInternalObject(object);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::classifyExistingTimelineLeafInternalObject(PyObject* args)
{
    PyObject* pyObject = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyObject)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyObject, &DocumentObjectPy::Type)) {
        PyErr_SetString(PyExc_TypeError, "Expected one document object");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* object = static_cast<DocumentObjectPy*>(pyObject)->getDocumentObjectPtr();
        if (!object || !document->containsObject(object) || object->getDocument() != document) {
            throw Py::ValueError("The existing internal leaf must be live in this document");
        }
        document->classifyExistingTimelineLeafInternalObject(object);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::classifyExistingTimelineSemanticBlockInternalObject(PyObject* args)
{
    PyObject* pyOperation = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyOperation)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOperation, &DocumentObjectPy::Type)) {
        PyErr_SetString(PyExc_TypeError, "Expected one document object");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* operation
            = static_cast<DocumentObjectPy*>(pyOperation)->getDocumentObjectPtr();
        if (!operation || !document->containsObject(operation)
            || operation->getDocument() != document) {
            throw Py::ValueError(
                "The legacy semantic root must be live in this document"
            );
        }
        document->classifyExistingTimelineSemanticBlockInternalObject(operation);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::isProvisionallyEnrolledInTimelineByCurrentTransaction(PyObject* args)
{
    PyObject* pyObject = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyObject)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyObject, &DocumentObjectPy::Type)) {
        PyErr_SetString(PyExc_TypeError, "Expected one document object");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* object = static_cast<DocumentObjectPy*>(pyObject)->getDocumentObjectPtr();
        if (!object || !document->containsObject(object) || object->getDocument() != document) {
            throw Py::ValueError(
                "The provisional-enrollment query requires one live object "
                "in this document"
            );
        }
        return Py::new_reference_to(
            Py::Boolean(document->isProvisionallyEnrolledInTimelineByCurrentTransaction(object))
        );
    }
    PY_CATCH;
}

PyObject* DocumentPy::isApplyingTimelineState(PyObject* args)
{
    if (!PyArg_ParseTuple(args, "")) {
        return nullptr;
    }

    PY_TRY
    {
        return Py::new_reference_to(Py::Boolean(getDocumentPtr()->isApplyingTimelineState()));
    }
    PY_CATCH;
}

PyObject* DocumentPy::isObjectUsableAtCurrentTimelinePosition(PyObject* args)
{
    PyObject* pyObject = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyObject)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyObject, &DocumentObjectPy::Type)) {
        PyErr_SetString(PyExc_TypeError, "Expected one document object");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* object = static_cast<DocumentObjectPy*>(pyObject)->getDocumentObjectPtr();
        return Py::new_reference_to(
            Py::Boolean(document->isObjectUsableAtCurrentTimelinePosition(object))
        );
    }
    PY_CATCH;
}

PyObject* DocumentPy::stageTimelineOperationSegmentReplacement(PyObject* args)
{
    PyObject* pySegments = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pySegments)) {
        return nullptr;
    }
    if (!PySequence_Check(pySegments)) {
        PyErr_SetString(PyExc_TypeError, "Expected a sequence of old-root sequences");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        Py::Object segments
            = snapshotPythonSequence(pySegments, "Old-root segments must be a sequence");
        const Py_ssize_t segmentCount = PySequence_Fast_GET_SIZE(segments.ptr());
        PyObject** segmentItems = PySequence_Fast_ITEMS(segments.ptr());
        std::vector<std::vector<DocumentObject*>> oldRootSegments;
        oldRootSegments.reserve(segmentCount);
        for (Py_ssize_t segmentIndex = 0; segmentIndex < segmentCount; ++segmentIndex) {
            if (!PySequence_Check(segmentItems[segmentIndex])) {
                throw Py::TypeError("Every staged segment must be a sequence of roots");
            }
            Py::Object roots = snapshotPythonSequence(
                segmentItems[segmentIndex],
                "Staged roots must be a sequence"
            );
            const Py_ssize_t rootCount = PySequence_Fast_GET_SIZE(roots.ptr());
            PyObject** rootItems = PySequence_Fast_ITEMS(roots.ptr());
            std::vector<DocumentObject*> oldRoots;
            oldRoots.reserve(rootCount);
            for (Py_ssize_t rootIndex = 0; rootIndex < rootCount; ++rootIndex) {
                if (!PyObject_TypeCheck(rootItems[rootIndex], &DocumentObjectPy::Type)) {
                    throw Py::TypeError("Every staged root must be a document object");
                }
                auto* root
                    = static_cast<DocumentObjectPy*>(rootItems[rootIndex])->getDocumentObjectPtr();
                if (!root || !document->containsObject(root) || root->getDocument() != document) {
                    throw Py::ValueError("Every staged root must be live in this document");
                }
                oldRoots.push_back(root);
            }
            oldRootSegments.push_back(std::move(oldRoots));
        }
        for (const auto& roots : oldRootSegments) {
            validateParsedDocumentObjects(
                document,
                roots,
                "A staged root was deleted while segment sequences were parsed"
            );
        }
        document->stageTimelineOperationSegmentReplacement(oldRootSegments);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::finalizeProvisionalTimelineOperationSegmentReplacement(PyObject* args)
{
    PyObject* pyMappings = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyMappings)) {
        return nullptr;
    }
    if (!PySequence_Check(pyMappings)) {
        PyErr_SetString(PyExc_TypeError, "Expected a sequence of five-item replacement mappings");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        Py::Object mappings
            = snapshotPythonSequence(pyMappings, "Replacement mappings must be a sequence");
        const Py_ssize_t mappingCount = PySequence_Fast_GET_SIZE(mappings.ptr());
        PyObject** mappingItems = PySequence_Fast_ITEMS(mappings.ptr());
        std::vector<TimelineSegmentReplacementMapping> parsed;
        parsed.reserve(mappingCount);
        for (Py_ssize_t mappingIndex = 0; mappingIndex < mappingCount; ++mappingIndex) {
            if (!PySequence_Check(mappingItems[mappingIndex])) {
                throw Py::TypeError("Every segment replacement mapping must be a sequence");
            }
            Py::Object mapping = snapshotPythonSequence(
                mappingItems[mappingIndex],
                "A segment replacement mapping must be a sequence"
            );
            if (PySequence_Fast_GET_SIZE(mapping.ptr()) != 5) {
                throw Py::TypeError(
                    "Every segment replacement mapping requires exactly "
                    "five fields"
                );
            }
            PyObject** fields = PySequence_Fast_ITEMS(mapping.ptr());

            const long stagedSegmentIndex = Py::Long(Py::Object(fields[0]));
            const long activeRootCount = Py::Long(Py::Object(fields[4]));
            if (stagedSegmentIndex < 0) {
                throw Py::ValueError("A staged segment index cannot be negative");
            }
            if (!PySequence_Check(fields[1]) || !PySequence_Check(fields[2])
                || !PySequence_Check(fields[3])) {
                throw Py::TypeError(
                    "Replacement blocks and state/consumer mappings must be "
                    "sequences"
                );
            }

            TimelineSegmentReplacementMapping result;
            result.stagedSegmentIndex = static_cast<std::size_t>(stagedSegmentIndex);
            result.activeRootCount = activeRootCount;

            Py::Object blocks
                = snapshotPythonSequence(fields[1], "Replacement blocks must be a sequence");
            const Py_ssize_t blockCount = PySequence_Fast_GET_SIZE(blocks.ptr());
            PyObject** blockItems = PySequence_Fast_ITEMS(blocks.ptr());
            result.orderedNewBlocks.reserve(blockCount);
            for (Py_ssize_t blockIndex = 0; blockIndex < blockCount; ++blockIndex) {
                if (!PySequence_Check(blockItems[blockIndex])) {
                    throw Py::TypeError(
                        "Every replacement block must be a sequence of "
                        "document objects"
                    );
                }
                Py::Object block = snapshotPythonSequence(
                    blockItems[blockIndex],
                    "A replacement block must be a sequence"
                );
                const Py_ssize_t objectCount = PySequence_Fast_GET_SIZE(block.ptr());
                PyObject** objectItems = PySequence_Fast_ITEMS(block.ptr());
                std::vector<DocumentObject*> objects;
                objects.reserve(objectCount);
                for (Py_ssize_t objectIndex = 0; objectIndex < objectCount; ++objectIndex) {
                    if (!PyObject_TypeCheck(objectItems[objectIndex], &DocumentObjectPy::Type)) {
                        throw Py::TypeError(
                            "Every replacement block member must be a "
                            "document object"
                        );
                    }
                    auto* object = static_cast<DocumentObjectPy*>(objectItems[objectIndex])
                                       ->getDocumentObjectPtr();
                    if (!object || !document->containsObject(object)
                        || object->getDocument() != document) {
                        throw Py::ValueError(
                            "Every replacement block member must be live in "
                            "this document"
                        );
                    }
                    objects.push_back(object);
                }
                result.orderedNewBlocks.push_back(std::move(objects));
            }

            const auto parseIndices = [](PyObject* value) {
                Py::Object sequence
                    = snapshotPythonSequence(value, "Replacement indices must be a sequence");
                const Py_ssize_t count = PySequence_Fast_GET_SIZE(sequence.ptr());
                PyObject** items = PySequence_Fast_ITEMS(sequence.ptr());
                std::vector<long> indices;
                indices.reserve(count);
                for (Py_ssize_t index = 0; index < count; ++index) {
                    indices.push_back(Py::Long(Py::Object(items[index])));
                }
                return indices;
            };
            result.stateSourceIndices = parseIndices(fields[2]);
            result.consumerReplacementIndices = parseIndices(fields[3]);
            parsed.push_back(std::move(result));
        }

        for (const auto& mapping : parsed) {
            for (const auto& block : mapping.orderedNewBlocks) {
                validateParsedDocumentObjects(
                    document,
                    block,
                    "A replacement block member was deleted while mappings were parsed"
                );
            }
        }
        document->finalizeProvisionalTimelineOperationSegmentReplacement(parsed);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::stageTimelineOperationResourceReconciliation(PyObject* args)
{
    PyObject* pyOwner = nullptr;
    PyObject* pyOldResourceRoots = nullptr;
    if (!PyArg_ParseTuple(args, "OO", &pyOwner, &pyOldResourceRoots)) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOwner, &DocumentObjectPy::Type)
        || !PySequence_Check(pyOldResourceRoots)) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected one document owner and a sequence of old resource roots"
        );
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* owner = static_cast<DocumentObjectPy*>(pyOwner)->getDocumentObjectPtr();
        if (!owner || !document->containsObject(owner) || owner->getDocument() != document) {
            throw Py::ValueError("The resource owner must be live in this document");
        }

        Py::Object roots
            = snapshotPythonSequence(pyOldResourceRoots, "Old resource roots must be a sequence");
        const Py_ssize_t rootCount = PySequence_Fast_GET_SIZE(roots.ptr());
        PyObject** rootItems = PySequence_Fast_ITEMS(roots.ptr());
        std::vector<DocumentObject*> oldResourceRoots;
        oldResourceRoots.reserve(rootCount);
        for (Py_ssize_t index = 0; index < rootCount; ++index) {
            if (!PyObject_TypeCheck(rootItems[index], &DocumentObjectPy::Type)) {
                throw Py::TypeError("Every old resource root must be a document object");
            }
            auto* resource = static_cast<DocumentObjectPy*>(rootItems[index])->getDocumentObjectPtr();
            if (!resource || !document->containsObject(resource)
                || resource->getDocument() != document) {
                throw Py::ValueError("Every old resource root must be live in this document");
            }
            oldResourceRoots.push_back(resource);
        }
        validateParsedDocumentObject(
            document,
            owner,
            "The resource owner was deleted while old-resource roots were parsed"
        );
        validateParsedDocumentObjects(
            document,
            oldResourceRoots,
            "An old resource root was deleted while its sequence was parsed"
        );
        document->stageTimelineOperationResourceReconciliation(owner, oldResourceRoots);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::finalizeProvisionalTimelineOperationResourceReconciliation(PyObject* args)
{
    PyObject* pyOwner = nullptr;
    PyObject* pyFinalResources = nullptr;
    PyObject* pyStateSources = nullptr;
    PyObject* pyConsumerReplacements = nullptr;
    if (
        !PyArg_ParseTuple(args, "OOOO", &pyOwner, &pyFinalResources, &pyStateSources, &pyConsumerReplacements)
    ) {
        return nullptr;
    }
    if (!PyObject_TypeCheck(pyOwner, &DocumentObjectPy::Type) || !PySequence_Check(pyFinalResources)
        || !PySequence_Check(pyStateSources) || !PySequence_Check(pyConsumerReplacements)) {
        PyErr_SetString(
            PyExc_TypeError,
            "Expected one document owner plus final-resource, state-source, "
            "and consumer-replacement sequences"
        );
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        auto* owner = static_cast<DocumentObjectPy*>(pyOwner)->getDocumentObjectPtr();
        if (!owner || !document->containsObject(owner) || owner->getDocument() != document) {
            throw Py::ValueError("The resource owner must be live in this document");
        }

        TimelineResourceReconciliationMapping mapping;
        mapping.owner = owner;
        Py::Object resources
            = snapshotPythonSequence(pyFinalResources, "Final resources must be a sequence");
        const Py_ssize_t resourceCount = PySequence_Fast_GET_SIZE(resources.ptr());
        PyObject** resourceItems = PySequence_Fast_ITEMS(resources.ptr());
        mapping.orderedFinalResources.reserve(resourceCount);
        for (Py_ssize_t index = 0; index < resourceCount; ++index) {
            if (!PyObject_TypeCheck(resourceItems[index], &DocumentObjectPy::Type)) {
                throw Py::TypeError("Every final resource must be a document object");
            }
            auto* resource
                = static_cast<DocumentObjectPy*>(resourceItems[index])->getDocumentObjectPtr();
            if (!resource || !document->containsObject(resource)
                || resource->getDocument() != document) {
                throw Py::ValueError("Every final resource must be live in this document");
            }
            mapping.orderedFinalResources.push_back(resource);
        }

        const auto parseIndices = [](PyObject* value) {
            Py::Object sequence
                = snapshotPythonSequence(value, "Resource reconciliation indices must be a sequence");
            const Py_ssize_t count = PySequence_Fast_GET_SIZE(sequence.ptr());
            PyObject** items = PySequence_Fast_ITEMS(sequence.ptr());
            std::vector<long> indices;
            indices.reserve(count);
            for (Py_ssize_t index = 0; index < count; ++index) {
                indices.push_back(Py::Long(Py::Object(items[index])));
            }
            return indices;
        };
        mapping.stateSourceIndices = parseIndices(pyStateSources);
        mapping.consumerReplacementIndices = parseIndices(pyConsumerReplacements);
        validateParsedDocumentObject(
            document,
            owner,
            "The resource owner was deleted while reconciliation sequences were parsed"
        );
        validateParsedDocumentObjects(
            document,
            mapping.orderedFinalResources,
            "A final resource was deleted while reconciliation sequences were parsed"
        );
        document->finalizeProvisionalTimelineOperationResourceReconciliation(mapping);
        Py_Return;
    }
    PY_CATCH;
}

PyObject* DocumentPy::semanticTimelineCopyClosure(PyObject* args)
{
    PyObject* pyObjects = nullptr;
    if (!PyArg_ParseTuple(args, "O", &pyObjects)) {
        return nullptr;
    }
    if (!PySequence_Check(pyObjects)) {
        PyErr_SetString(PyExc_TypeError, "Expected a sequence of document objects");
        return nullptr;
    }

    PY_TRY
    {
        auto* document = getDocumentPtr();
        Py::Object sequence
            = snapshotPythonSequence(pyObjects, "Semantic copy inputs must be a sequence");
        const Py_ssize_t sequenceSize = PySequence_Fast_GET_SIZE(sequence.ptr());
        PyObject** sequenceItems = PySequence_Fast_ITEMS(sequence.ptr());
        std::vector<DocumentObject*> selected;
        selected.reserve(sequenceSize);
        std::unordered_set<DocumentObject*> seen;
        for (Py_ssize_t index = 0; index < sequenceSize; ++index) {
            if (!PyObject_TypeCheck(sequenceItems[index], &DocumentObjectPy::Type)) {
                throw Py::TypeError("Every semantic copy input must be a document object");
            }
            auto* object = static_cast<DocumentObjectPy*>(sequenceItems[index])->getDocumentObjectPtr();
            if (!object || !document->containsObject(object) || object->getDocument() != document
                || !seen.insert(object).second) {
                throw Py::ValueError(
                    "Semantic copy inputs must be distinct live objects "
                    "in this document"
                );
            }
            selected.push_back(object);
        }

        validateParsedDocumentObjects(
            document,
            selected,
            "A semantic copy input was deleted while its sequence was parsed"
        );
        const auto* timeline = DocumentTimeline::get(document);
        if (!timeline) {
            throw Py::RuntimeError("This document has no native timeline");
        }
        const auto closure = timeline->semanticCopyClosure(selected);
        Py::Tuple result(closure.size());
        for (std::size_t index = 0; index < closure.size(); ++index) {
            result.setItem(index, Py::Object(closure[index]->getPyObject(), true));
        }
        return Py::new_reference_to(result);
    }
    PY_CATCH;
}


Py::Boolean DocumentPy::getRestoring() const
{
    return {getDocumentPtr()->testStatus(Document::Status::Restoring)};
}

Py::Boolean DocumentPy::getPartial() const
{
    return {getDocumentPtr()->testStatus(Document::Status::PartialDoc)};
}

Py::Boolean DocumentPy::getImporting() const
{
    return {getDocumentPtr()->testStatus(Document::Status::Importing)};
}

Py::Boolean DocumentPy::getRecomputing() const
{
    return {getDocumentPtr()->testStatus(Document::Status::Recomputing)};
}

Py::Boolean DocumentPy::getRecomputePending() const
{
    const auto* document = getDocumentPtr();
    return {GetApplication().hasPendingRecomputeRequest(document->getName())};
}

Py::Boolean DocumentPy::getTransacting() const
{
    return {getDocumentPtr()->isPerformingTransaction()};
}

Py::String DocumentPy::getOldLabel() const
{
    return {getDocumentPtr()->getOldLabel()};
}

Py::Boolean DocumentPy::getTemporary() const
{
    return {getDocumentPtr()->testStatus(Document::TempDoc)};
}
