# SPDX-License-Identifier: LGPL-2.1-or-later

from . import TestBoolean
from . import TestChamfer
from . import TestContextMenuTracking
from . import TestDatum
from . import TestDraft
from . import TestExactTransactionContract
from . import TestFillet
from . import TestFeatureBasePlacement
from . import TestFeatureTimeline
from . import TestHelix
from . import TestHole
from . import TestInvoluteGear
from . import TestLinearPattern
from . import TestLoft
from . import TestMirrored
from . import TestMultiTransform
from . import TestModelTreeBrowser
from . import TestNativeRibbonTools
from . import TestNativeTaskContract
from . import TestPartMultiInputRibbonTools
from . import TestPartDesignTaskLifecycle
from . import TestPythonFeatureTasks
from . import TestPartSingleInputRibbonTools
from . import TestRibbonInspectView
from . import TestPad
from . import TestPipe
from . import TestPocket
from . import TestPolarPattern
from . import TestPrimitive
from . import TestRetainedPartDialogs
from . import TestRevolve
from . import TestShapeBinder
from . import TestSuppressed
from . import TestThickness
from . import TestTopologicalNamingProblem
