# SPDX-License-Identifier: LGPL-2.1-or-later

# Kuka export lib (c) Jürgen Riegel 2009 LGPL 2.1 or higher

import re
import time
from pathlib import Path

TeachPointFold = """
;FOLD LIN P4  Vel= 0.2 m/s CPDAT1 Tool[1] Base[0];%{PE}%R 5.4.27,%MKUKATPBASIS,%CMOVE,%VLIN,%P 1:LIN, 2:P4, 3:, 5:0.2, 7:CPDAT1
$BWDSTART = FALSE
LDAT_ACT=LCPDAT1
FDAT_ACT=FP4
BAS(#CP_PARAMS,0.2)
LIN XP4
;ENDFOLD
"""

TeachPointDat = """
DECL E6POS XP4={X -25.1844196,Y 1122.42603,Z 1158.07996,A -14.3267002,B 0.537901878,C 179.028305,S 6,T 59,E1 0.0,E2 0.0,E3 0.0,E4 0.0,E5 0.0,E6 0.0}
DECL FDAT FP4={TOOL_NO 1,BASE_NO 0,IPO_FRAME #BASE,POINT2[] " "}
DECL LDAT LCPDAT1={VEL 2.0,ACC 100.0,APO_DIST 100.0,APO_FAC 50.0,ORI_TYP #VAR}
"""

HeaderSrc = r"""&ACCESS RVP
&REL 1
&PARAM TEMPLATE = C:\KRC\Roboter\Template\ExpertVorgabe
&PARAM EDITMASK = *
"""


def _program_name(trajectory):
    raw = getattr(trajectory, "Name", "") or "VIBECAD_PATH"
    name = re.sub(r"[^A-Za-z0-9_]", "_", raw).strip("_")
    if not name:
        name = "VIBECAD_PATH"
    if name[0].isdigit():
        name = "P_" + name
    return name[:24]


def _waypoints(trajectory):
    points = list(trajectory.Trajectory.Waypoints)
    if not points:
        raise ValueError("The selected trajectory has no waypoints to export")
    return points


def _src_path(file_name):
    path = Path(file_name).expanduser()
    return path if path.suffix.lower() == ".src" else path.with_suffix(".src")


def _pose(waypoint):
    a, b, c = waypoint.Pos.Rotation.toEuler()
    return (
        waypoint.Pos.Base.x,
        waypoint.Pos.Base.y,
        waypoint.Pos.Base.z,
        a,
        b,
        c,
    )


def _motion_settings(waypoint):
    velocity = max(float(waypoint.Velocity) / 1000.0, 0.001)
    acceleration = max(float(waypoint.Acceleration) / 1000.0, 0.001)
    continuation = " C_DIS" if bool(waypoint.Cont) else ""
    return velocity, acceleration, continuation


def _write_header(stream, program_name):
    stream.write(HeaderSrc)
    stream.write(f"DEF {program_name}( )\n\n")
    stream.write(";- KUKA KRL generated by VibeCAD\n")
    stream.write(f";- {time.asctime()}\n\n")
    stream.write("EXT BAS (BAS_COMMAND :IN, REAL :IN)\n")
    stream.write("BAS(#INITMOV, 0)\n\n")


def ExportCompactSub(Rob, Trak, FileName):
    del Rob  # The exported Cartesian path is independent of the robot display model.
    points = _waypoints(Trak)
    source_path = _src_path(FileName)
    source_path.parent.mkdir(parents=True, exist_ok=True)
    program_name = _program_name(Trak)

    with source_path.open("w", encoding="utf-8", newline="\n") as stream:
        _write_header(stream, program_name)
        for index, waypoint in enumerate(points, start=1):
            x, y, z, a, b, c = _pose(waypoint)
            velocity, acceleration, continuation = _motion_settings(waypoint)
            stream.write(f"$VEL.CP = {velocity:.6f}\n")
            stream.write(f"$ACC.CP = {acceleration:.6f}\n")
            stream.write(
                "LIN {"
                f"X {x:.3f}, Y {y:.3f}, Z {z:.3f}, "
                f"A {a:.3f}, B {b:.3f}, C {c:.3f}"
                f"}}{continuation} ; P{index}: {waypoint.Name}\n"
            )
        stream.write("\nEND\n")


def ExportFullSub(Rob, Trak, FileName):
    del Rob
    points = _waypoints(Trak)
    source_path = _src_path(FileName)
    data_path = source_path.with_suffix(".dat")
    source_path.parent.mkdir(parents=True, exist_ok=True)
    program_name = _program_name(Trak)

    with source_path.open("w", encoding="utf-8", newline="\n") as stream:
        _write_header(stream, program_name)
        for index, waypoint in enumerate(points, start=1):
            velocity, acceleration, continuation = _motion_settings(waypoint)
            stream.write(f"$VEL.CP = {velocity:.6f}\n")
            stream.write(f"$ACC.CP = {acceleration:.6f}\n")
            stream.write(f"LIN XP{index}{continuation} ; {waypoint.Name}\n")
        stream.write("\nEND\n")

    with data_path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write(HeaderSrc)
        stream.write(f"DEFDAT {program_name} PUBLIC\n\n")
        for index, waypoint in enumerate(points, start=1):
            x, y, z, a, b, c = _pose(waypoint)
            stream.write(
                f"DECL E6POS XP{index}={{"
                f"X {x:.3f}, Y {y:.3f}, Z {z:.3f}, "
                f"A {a:.3f}, B {b:.3f}, C {c:.3f}, "
                "S 6, T 35, "
                "E1 0.0, E2 0.0, E3 0.0, "
                "E4 0.0, E5 0.0, E6 0.0"
                "}\n"
            )
        stream.write("\nENDDAT\n")
